version: "3.8"

networks:
  api_rabbitmq:
    external: true

services:
  app:
    image: node:15
    working_dir: /usr/src/svc
    env_file: .env
    volumes:
      - .:/usr/src/svc
    expose:
      - "4100"
    command: "npm run dev:start"
    networks:
      - api_rabbitmq
